name: Create New Project

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Project title'
        required: true
      desc:
        description: 'Project description'
        required: true
      readme:
        description: 'README content'
        required: true

env:
  repo: ${{ github.repository }}
  org: ${{ github.repository_owner }}
  title: ${{ github.event.inputs.title }}
  desc: ${{ github.event.inputs.desc }}
  readme: ${{ github.event.inputs.readme }}
  GH_TOKEN: ${{ github.token }}
  # GH_TOKEN: ${{ secrets.PROJECT_TOKEN }}

jobs:
  create-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GitHub CLI
      uses: ksivamuthu/actions-setup-gh-cli@v3

    - name: Create GitHub project and issues
      run: |
        project=$(gh project create --owner "$org" --title "$title" --format json --jq .number)
        # gh project edit $project --description "$desc" --readme "$readme"
        # gh project link $project
        # gh project link $project --owner "$org" --team "curation-and-recruitment"
        echo "Title: $title"
        echo "Desc: $desc"
        echo "Readme: $readme"
        for file in issue_template/*.md; do
          issue_title="$title - $(basename ${file%.md} | tr '_' ' ' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))}1')"
          gh issue -R "$repo" create --title "$issue_title" --body-file "$file" --project "$title"
        done
